# Generated by Django 4.1.3 on 2022-11-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monsterdatabase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monster",
            name="private",
        ),
    ]
